name: cs_6
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.11.11
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    - google
    - google-genai
    - python-dotenv
    - Flask
    - google-generativeai
